POST http://localhost:3000/users
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
    "name":"Меместо",
    "about":"Место ваших мемов",
    "avatar":"https://memepedia.ru/wp-content/uploads/2017/08/1492860042_e-news.su_ohuitelnye-istorii.gif",
    "email":"user@test.com",
    "password":"jopa lala"
}

###

GET http://localhost:3000/users
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: {{token}}

###

GET http://localhost:3000/users/me
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: {{token}}

###

GET http://localhost:3000/users/{{user2}}
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: {{token}}

###

PATCH http://localhost:3000/users/me
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: {{token}}

{
    "name":"Меместограм",
    "about":"Инстаграм мемных мест"
}

###

PATCH http://localhost:3000/users/me/avatar
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: {{token}}

{
    "avatar":"https://memepedia.ru/wp-content/uploads/2019/03/u-suka-10.jpg"
}

###
